### PR TITLE
Updates to produce new, better phenotype comparisons

### PR DESCRIPTION
**Pull request by caufieldjh**

### CODE REVIEW

**Comment by caufieldjh** [comment]
This currently will generate the IC maps but won't yet pass them to the call to `runoak similarity`

**Comment by caufieldjh** [comment]
On the Jenkins run, the line for building the custom IC map fails due to an SQL error, as below:

```
09:33:34  + runoak -g hpoa.tsv -G hpoa -i sqlite:obo:phenio information-content -p i --use-associations .all
12:32:40  sqlite3.OperationalError: too many SQL variables
12:32:40  
12:32:40  The above exception was the direct cause of the following exception:
12:32:40  
12:32:40  sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) too many SQL variables
12:32:40  [SQL: SELECT term_association.id AS term_association_id, term_association.subject AS term_association_subject, term_association.predicate AS term_association_predicate, term_association.object AS term_association_object, term_association.evidence_type AS term_association_evidence_type, term_association.publication AS term_association_publication, term_association.source AS term_association_source 
12:32:40  FROM term_association 
12:32:40  WHERE term_association.object IN (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?,
```

**Comment by caufieldjh** [comment]
This may require sqlite to be updated on the build environment.
See also https://github.com/deepset-ai/haystack/issues/588

**Comment by caufieldjh** [comment]
With changes in https://github.com/INCATools/ontology-access-kit/pull/764 I expect this to work better - will just need to pin OAK version to github

**Comment by caufieldjh** [comment]
Will test after merging https://github.com/INCATools/ontology-access-kit/pull/759

**Comment by caufieldjh** [comment]
Getting Jenkins errors on test - unclear why:
```
Error when executing always post condition:
Also:   org.jenkinsci.plugins.workflow.actions.ErrorAction$ErrorId: 7c6506e2-fc79-47e8-b60a-bfd6d52143dd
org.jenkinsci.plugins.workflow.steps.MissingContextVariableException: Required context class hudson.FilePath is missing
Perhaps you forgot to surround the code with a step that provides this, such as: node
	at org.jenkinsci.plugins.workflow.steps.CoreStep$Execution.run(CoreStep.java:89)
	at org.jenkinsci.plugins.workflow.steps.CoreStep$Execution.run(CoreStep.java:70)
	at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution.lambda$start$0(SynchronousNonBlockingStepExecution.java:47)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

**Comment by caufieldjh** [comment]
The Jenkins error was due to string interpolation in environment variable names not working as expected.

**Comment by caufieldjh** [comment]
Getting a `ModuleNotFoundError: No module named 'semsimian'` because semsimian is optional dependency - fixing

**Comment by caufieldjh** [comment]
Good news: IC map is produced quickly and without errors!
Bad news: Something (OAK or Semsimian) is raising an error:
```
10:13:21  + runoak -i semsimian:sqlite:obo:phenio similarity --no-autolabel --information-content-file hpoa_ic.tsv -p i --set1-file HPO_terms.txt --set2-file HPO_terms.txt -O csv -o HP_vs_HP_semsimian_-20240516.tsv --min-ancestor-information-content 4.0
10:13:39  Loading custom IC map from: "hpoa_ic.tsv"
10:13:39  Failed to import custom IC map: Error parsing IC value: invalid float literal
```

**Comment by caufieldjh** [comment]
That error may be a false positive - when I run a single pair locally and pass the IC map, I don't get that error:
```
$ runoak -vvv -i semsimian:sqlite:obo:phenio similarity --no-autolabel --information-content-file hpoa_ic.tsv -p i  -O csv -o test.tsv --min-ancestor-information-content 4.0 HP:
0007166 @ HP:0007153
INFO:root:Setting other_languages=()
INFO:root:Settings = Settings(impl=None, autosave=False, associations_type=None, preferred_language=None, other_languages=())
INFO:root:Wrapping an existing OAK implementation to fetch sqlite:obo:phenio
INFO:root:Locator: obo:phenio
INFO:root:Ensuring gunzipped for https://s3.amazonaws.com/bbop-sqlite/phenio.db.gz
INFO:root:Locator, post-processed: sqlite:////home/harry/.data/oaklib/phenio.db
DEBUG:root:Paths to search: [PurePosixPath('model/schema'), PurePosixPath('schema'), PurePosixPath('linkml'), PurePosixPath('src/linkml'), PurePosixPath('src/model'), PurePosixPath('src/model/schema'), PurePosixPath('src/schema'), PurePosixPath('.')]
DEBUG:root:candidate model/schema not found
DEBUG:root:candidate schema not found
DEBUG:root:candidate linkml not found
DEBUG:root:candidate src/linkml not found
DEBUG:root:candidate src/model not found
DEBUG:root:candidate src/model/schema not found
DEBUG:root:candidate src/schema not found
INFO:root:out=test.tsv <class 'str'>
INFO:root:file=<_io.TextIOWrapper name='test.tsv' mode='w' encoding='UTF-8'> <class 'str'>
INFO:root:Splitting terms ['HP:0007166', '@', 'HP:0007153'] on 1
INFO:root:Calculating all-by-all pairwise similarity for 1 objects
[00:00:09] Building closure and IC map: ████████████████████████████████████████ 100%                                                                                                                                             INFO:root:Post-processing results from semsimian
```

This is the relevant function in semsimian:
https://github.com/monarch-initiative/semsimian/blob/e2cba82624dc0633092e0b299d80f3771d01659c/src/utils.rs#L579-L607

Maybe it's just trying to parse EOF? Seems unlikely as there isn't a tab in the last line.

Oh. Wait. No. It's the *header*.
Semsimian doesn't expect it.
Not sure why that error isn't being raised locally but I'll put a fix for it in here.

**Comment by caufieldjh** [comment]
Looks like the map is now loading correctly, at least for HP.
```
12:14:28  + runoak -i semsimian:sqlite:obo:phenio similarity --no-autolabel --information-content-file hpoa_ic.tsv -p i --set1-file HPO_terms.txt --set2-file HPO_terms.txt -O csv -o HP_vs_HP_semsimian_-20240516.tsv --min-ancestor-information-content 4.0
12:14:46  Loading custom IC map from: "hpoa_ic.tsv"
12:14:46  Custom IC map imported successfully.
12:14:55  Warning: The following keys are present in closure_map but not in ic_map:
```
This is followed by a list of more than 20K CURIEs, including 5952 HP IDs.
Might be excessive to write that to stdout.

**Comment by justaddcoffee** [comment]
I wonder why so many CURIEs are in closure_map but not ic_map?

**Comment by caufieldjh** [comment]
If the HP ID doesn't show up in the association table at all, it doesn't get an IC score.
So many of these IDs (just based on cursory checking, not exhaustive at all) are rare phenotypes, like HP:0100378 (Absent distal phalanx of the 3rd toe) or high-level terms that just aren't specific enough to get used in associations, like HP:0008008 (Reduced visual acuity) - the latter's child term of HP:0000618 (Blindness) is used 168 times in the HPOA, for example.

Is this the expected behavior, though?
Should all terms receive some sort of baseline score by virtue of existing, then have that score get adjusted proportionally by observed frequency?

**Comment by justaddcoffee** [comment]
> Is this the expected behavior, though?

This is expected, but is going to cause problems. I think we will need IC values for everything in phenio

> Should all terms receive some sort of baseline score by virtue of existing, then have that score get adjusted proportionally by observed frequency?

We could do that, but I can't think of how to convince OAK to calculate IC like that.

How about this: if a term is not observed, we set the IC to -log(1/number of total counts). 

To do this, we could post-process the IC tsv file to set any term in phenio that isn't in there to min(IC score in the IC TSV file). Or, we could do this in semsimian after we read in the IC tsv file.

**Comment by caufieldjh** [comment]
TODO:
* Add option to semsimian + OAK to specify what to do for CURIEs in closure but not in IC map. One option should be to fail. Don't do that by default. Also provide option to infer (assign or use proportional IC.
* Save other artifacts to the uploaded output, like the IC maps.

**Comment by caufieldjh** [comment]
Also something odd happened to the HPvMP and HPvZP uploads. Will check on that

**Comment by caufieldjh** [comment]
Aha - the issue is that the IC tables for MP and ZP aren't generating what I'd expect.
Running this:
```
runoak -g mpa.tsv -G hpoa_g2p -i sqlite:obo:phenio information-content -p i --use-associations .all > mpa_ic.tsv
```
Only outputs 137 ICs, _none_ of them from MP! It looks like the `subject_taxon` column is being used as the calculation input instead of what's in the `object` column. 
So the `hpoa_g2p` parser isn't working as expected.
Other parsers are listed here: https://github.com/INCATools/ontology-access-kit/blob/main/src/oaklib/parsers/__init__.py

**Pull request merged**
